name: Package Addon

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SVN (Subversion)
        run: sudo apt update && sudo apt install subversion -y

      - name: Run the Packager
        run: |
          chmod +x .release/release.sh
          ./.release/release.sh

      - name: List files (debugging)
        run: ls -R .release

      - name: Upload Packaged Addon as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: packaged-addon
          path: .release/*.zip

      - name: Upload ZIP to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: .release/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
