name: Package Addon

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SVN (Subversion)
        run: sudo apt update && sudo apt install subversion -y

      - name: Run the Packager
        run: |
          chmod +x .release/release.sh
          ./.release/release.sh
